name = "classicravi-project-show-case-project-sparkle-and-shine-67-main"
main = ".output/server/index.mjs"
compatibility_date = "2026-08-04"
compatibility_flags = ["nodejs_compat"]
no_bundle = true

[assets]
binding = "ASSETS"
directory = ".output/public"

[build]
command = "npm install && npm run build"

[[rules]]
type = "ESModule"
globs = ["**/*.mjs", "**/*.js"]
